providers = ['python']

[phases.setup]
    nixPkgs = ['...', 'unzip']

[phases.init]
    dependsOn = ['install']
    cmds = ['reflex init']

[start]
    cmd = 'reflex run --frontend-only --env $ENV --loglevel debug'