providers = ['python']

[variables]
    NEXT_TELEMETRY_DISABLED = '1'

# [phases.node]
#     nixPkgs = ['nodejs']

# [phases.bun]
#     nixPkgs = ['bun']

[phases.setup]
    nixPkgs = ['...', 'unzip']

# [phases.python]
#     dependsOn = ['setup']
#     nixPkgs = ['python311', 'python311Packages.pip']

# [phases.install]
#     dependsOn = ['python']
#     cmds = ['pip install -r requirements.txt']

[phases.init]
    dependsOn = ['install']
    cmds = ['reflex init']

[phases.export]
    dependsOn = ['init']
    cmds = ['reflex export --frontend-only --no-zip']

[phases.caddy]
    dependsOn = ['export']
    nixpkgsArchive = 'bccff6f3ef29ef91701340cfabf6e6012802cbac'
    nixPkgs = ['caddy']

[start]
    cmd = 'caddy run 2>&1'