providers = ['python']

[variables]
    NEXT_TELEMETRY_DISABLED = '1'
    NPM_CONFIG_UPDATE_NOTIFIER = 'false' # the update notification is relatively useless in a production environment
    NPM_CONFIG_FUND = 'false' # the fund notification is also pretty useless in a production environment

[phases.setup]
    nixPkgs = ['...', 'unzip', 'parallel']

[phases.init]
    dependsOn = ['install']
    cmds = ['reflex init']

[phases.export]
    dependsOn = ['init']
    cmds = ['reflex export --frontend-only --no-zip']

[phases.caddy]
    dependsOn = ['export']
    nixpkgsArchive = 'bccff6f3ef29ef91701340cfabf6e6012802cbac'
    nixPkgs = ['caddy']

[start]
    cmd = 'parallel --halt now,fail=1 ::: "reflex run --backend-only --env $ENV" "caddy run 2>&1"'